### PR TITLE
Adding a new link to Docs in SubNav

### LINKED ISSUE #783: Add Docs link bottom left
Book Icon with Docs (links to Zesty.org)

image

### PR DESCRIPTION
**Pull request by d88naimi**
fixes #783

Screen Shot 2021-07-02 at 10 48 38 AM
Screen Shot 2021-07-02 at 10 48 44 AM

### CODE REVIEW

**Comment by shrunyan** [comment]
What is the difference between docs and help?

**Comment by d88naimi** [comment]
A easier access to directly link the user to zesty.org

**Comment by shrunyan** [comment]
So why are we keeping help if they ultimate go to the same place? Aren't these just duplicates?

**Comment by d88naimi** [comment]
After a discussion with @ardeay we decided to swap the help icon and title to Docs and Book icon while keeping all functionality the same.

Screen Shot 2021-07-02 at 4 18 29 PM

**Comment by ardeay** [comment]
👍

**Review by shrunyan — APPROVED** [review]

**Pull request merged**
