### PR TITLE
Content Recolor: Various color updates for content app

### PR DESCRIPTION
**Pull request by theofficialnar**
- Updated right sidebar cards design
- Added custom theme for content app
- Updated nav color scheme
- Updated content list style
- Updated dashboard style

### Note: these changes heavily rely on the following PRs to be published for the colors to be right
- https://github.com/zesty-io/material/pull/76
- https://github.com/zesty-io/design-system/pull/202

image
image
image

### CODE REVIEW

**Comment by shrunyan** [comment]
Content app nav is missing a background and so displays broken when hovered in a collapsed state. 
image

**Comment by shrunyan** [comment]
On the content list view unpublished items are showing an eye icon colored as orange. Historically we have used orange to indicate a scheduled item. I think this coloring will be very confusing. 

image

**Comment by shrunyan** [comment]
Hover state on "Create Blog Post" button is blue. Should be the shaded orange
image

**Comment by theofficialnar** [comment]
Hi @shrunyan, pushed fixes for the comments raised. Also, there are some dependencies on zesty-io/material and zesty-io/core that are needed for some of the changes here to make sense. It seems like what's deployed on stage are missing those.

Related PR needed to be reviewed and published:
https://github.com/zesty-io/material/pull/76
https://github.com/zesty-io/design-system/pull/202

**Pull request merged**
