### PR TITLE
Feature/#607 use domain universal

### PR DESCRIPTION
**Pull request by d88naimi**
@shrunyan I have gone ahead and converted Robot.js file from a class component to a functional component to the best of my knowledge. I am able to render the page however functionality is not working. Can you please review and point me in the right direction thank you.

### CODE REVIEW

**Comment by shrunyan** [comment]
I am not sure exactly what functionality is not working and needs direction.

Looking at the branch I can see the save request is failing. Currently it is using a POST and I think needs to be a PUT. Confirm with @crzestyio if that does not work.

**Comment by d88naimi** [comment]
@shrunyan I got Robot.js working this morning I believe this is ready for review.

**Comment by crzestyio** [comment]
@d88naimi It is a PUT

**Comment by d88naimi** [comment]
@shrunyan I fixed save last night and seeing the PUT request. I believe this is ready for review thank you.

**Pull request closed without merging**
