### PR TITLE
Feature/#643 SEO wildcard fix jumping cursor, fixed alignment header to body table

### LINKED ISSUE #643: SEO: Wildcard redirects
**Is your feature request related to a problem? Please describe.**
WebEngine now supports wildcard redirects, as well as 3 types of redirects `path`, `external`, and `page` that are not available to customers through the current redirects UI

**Describe the solution you'd like**
We should update the app to give the user three options to make a redirect and include links to documentation.
**Describe alternatives you've considered**

API Documentation on this feature is located: https://instances-api.zesty.org/#1fdabbe3-e977-4ea5-8a4b-81ce29598263

Individual APi docs for the different types of redirects
* `path`: https://instances-api.zesty.org/#38bf3fb8-44b1-4b22-a743-376c42fda624
* `path` with Wildcard: https://instances-api.zesty.org/#4e35194e-ce30-43a0-bfe2-91bc76e5a627
* `page` (ZUID): https://instances-api.zesty.org/#9dbf6a75-cb3e-4292-850b-1e78979bd035
* `external`: https://instances-api.zesty.org/#0e1a4940-3d7f-4e59-bd3d-9b06be44d9a3

Zesty.org docs https://zesty.org/services/web-engine/30x-redirects

## Desired Update

The current UI only creates a `path`, the UI should be updated to create the 3 types of redirects.

The current UI lends itself to to work with a couple changes:

**Change 1:** The dropdown search for pages should stay, but on select it should populate with a ZUID
**Change 2:**  The "to" input should not strictly enforce the value to a path, but also a ZUID or full URL with protocol
**Change 3:** Type assumption should be made based in on the incoming string. This would change the post request type value. An assumption on the incoming target string can be made like this:
* any string that include HTTP is of type `external`
* any string with a ZUID (7-xyz-xyz) is of type `page`
* If the above does not match, default to type `path`

Change 4: Titles should change from "From" to "Incoming Path" and "To" to "Redirect Target"

### PR DESCRIPTION
**Pull request by d88naimi**
fixes #643 

Screen Shot 2021-08-19 at 3 24 26 PM

### CODE REVIEW

**Comment by shrunyan** [comment]
Nice.This is getting close.

**Comment by shrunyan** [comment]
@d88naimi would you also coordinate with @giseleblair on testing the CSV import to ensure that continues to function with these changes.

**Comment by d88naimi** [comment]
V3 
Screen Shot 2021-08-20 at 2 05 21 PM

**Comment by d88naimi** [comment]
@shrunyan @ardeay After testing with @giseleblair the import CSV is not accounting for the new dropdown Redirect Types.

I putting this PR back into draft until I can get those functionality and styles updated.

Screen Shot 2021-08-20 at 7 35 23 PM

**Comment by d88naimi** [comment]
Updated SEO redirect import styles to be consistent with SEO redirect page 

Before 
Screen Shot 2021-08-24 at 10 04 16 AM

After
Screen Shot 2021-08-24 at 10 04 06 AM

Pre existing view
Screen Shot 2021-08-24 at 10 29 13 AM

**Review by shrunyan — APPROVED** [review]

**Pull request merged**
