### PR TITLE
FIX: Add an error message screen when model fails to load

### LINKED ISSUE #1618: TypeError: Cannot read properties of undefined (reading 'type')
Sentry Issue: [MANAGER-UI-1VD](https://sentry.io/organizations/zestyio/issues/3730003569/?referrer=github_integration)

```
React ErrorBoundary Error: Cannot read properties of undefined (reading 'type')
  at Actions (./src/apps/content-editor/src/app/views/ItemEdit/Content/Actions/Actions.js:21:14)
  at ActionsDrawer (./src/apps/content-editor/src/app/views/ItemEdit/Content/ActionsDrawer/ActionsDrawer.js:25:20)
  at Content (./src/apps/content-editor/src/app/views/ItemEdit/Content/Content.js:12:14)
  at ItemEdit (./src/apps/content-editor/src/app/views/ItemEdit/ItemEdit.js:65:20)
  at Up (./src/apps/content-editor/src/app/ContentEditor.js:29:25)
...
(23 additional frame(s) were not displayed)

TypeError: Cannot read properties of undefined (reading 'type')
  at Actions (./src/apps/content-editor/src/app/views/ItemEdit/Content/Actions/Actions.js:31:11)
...
(11 additional frame(s) were not displayed)
```

./src/apps/content-editor/src/app/views/ItemEdit/Content/Actions/Actions.js in Actions at line 31:11
`const { type } = props.model;`

### LINKED ISSUE #1739: TypeError: Cannot read properties of undefined (reading 'ZUID')
Sentry Issue: [MANAGER-UI-1TE](https://sentry.io/organizations/zestyio/issues/3696977529/?referrer=github_integration)

```
React ErrorBoundary Error: Cannot read properties of undefined (reading 'ZUID')
  at xu (./src/apps/content-editor/src/app/components/Editor/Editor.js:10:3)
  at Content (./src/apps/content-editor/src/app/views/ItemEdit/Content/Content.js:12:14)
  at ItemEdit (./src/apps/content-editor/src/app/views/ItemEdit/ItemEdit.js:65:20)
  at Pp (./src/apps/content-editor/src/app/ContentEditor.js:29:25)
  at Mb (./src/shell/views/Shell/Shell.js:29:20)
...
(22 additional frame(s) were not displayed)

TypeError: Cannot read properties of undefined (reading 'ZUID')
  at xu (./src/apps/content-editor/src/app/components/Editor/Editor.js:155:43)
  at call (./src/apps/content-editor/src/app/views/ItemEdit/ItemEdit.js:162:9)
...
(18 additional frame(s) were not displayed)
```

### LINKED ISSUE #1809: TypeError: Cannot read properties of undefined (reading 'type')
Sentry Issue: [MANAGER-UI-1N4](https://zestyio.sentry.io/issues/3441811415/?referrer=github_integration)

```
React ErrorBoundary Error: Cannot read properties of undefined (reading 'type')
  at Actions (./src/apps/content-editor/src/app/views/ItemEdit/Content/Actions/Actions.js:21:14)
  at ActionsDrawer (./src/apps/content-editor/src/app/views/ItemEdit/Content/ActionsDrawer/ActionsDrawer.js:25:20)
  at Content (./src/apps/content-editor/src/app/views/ItemEdit/Content/Content.js:12:14)
  at ItemEdit (./src/apps/content-editor/src/app/views/ItemEdit/ItemEdit.js:65:20)
  at Xp (./src/apps/content-editor/src/app/ContentEditor.js:29:25)
...
(23 additional frame(s) were not displayed)

TypeError: Cannot read properties of undefined (reading 'type')
  at Actions (./src/apps/content-editor/src/app/views/ItemEdit/Content/Actions/Actions.js:31:11)
  at call (./src/apps/content-editor/src/app/views/ItemEdit/ItemEdit.js:162:9)
...
(15 additional frame(s) were not displayed)
```

### LINKED ISSUE #2000: TypeError: Cannot read properties of undefined (reading 'type')
Sentry Issue: [MANAGER-UI-20H](https://zestyio.sentry.io/issues/4080792494/?referrer=github_integration)

```
React ErrorBoundary Error: Cannot read properties of undefined (reading 'type')
  at Actions (./src/apps/content-editor/src/app/views/ItemEdit/Content/Actions/Actions.js:21:14)
  at ActionsDrawer (./src/apps/content-editor/src/app/views/ItemEdit/Content/ActionsDrawer/ActionsDrawer.js:25:20)
  at Content (./src/apps/content-editor/src/app/views/ItemEdit/Content/Content.js:12:14)
  at ItemEdit (./src/apps/content-editor/src/app/views/ItemEdit/ItemEdit.js:65:20)
  at km (./src/apps/content-editor/src/app/ContentEditor.js:29:25)
...
(21 additional frame(s) were not displayed)

TypeError: Cannot read properties of undefined (reading 'type')
  at Actions (./src/apps/content-editor/src/app/views/ItemEdit/Content/Actions/Actions.js:31:11)
...
(45 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by JacobDiazCruz**
Closes #1618 
Closes #2000 
Closes #1809 
Closes #1739 

image

### CODE REVIEW

**Comment by JacobDiazCruz** [comment]
In any case, model prop/object should always have values since content items with SEO & meta are always dependent on them. The only thing that I can’t see is the empty "type" value within the model object. Which leads me to just applying a default string in case the "type" is undefined.

**Comment by JacobDiazCruz** [comment]
Unfortunately, I can't replicate this issue on dev and I added a comment regarding that on the bug ticket #1618.

1. Upon checking again, the child components that contains this "type" prop is unused. So I can still safely perform actions and there are no effects if the type field is empty string.

2. There is a loading state when the models are still fetching on the parent component, so the Action component won't render before that.

**Comment by JacobDiazCruz** [comment]
Got it, I think its best to just remove this code.

**Comment by theofficialnar** [comment]
Rendering the `<NotFound /> `component when `prop.model` is empty also fixes the issue raised on #1768

**Comment by theofficialnar** [comment]
> @theofficialnar This does not seem right to me.
> 
> We already have handling for this so this is redundant.
> 
> Screen Shot 2023-05-07 at 8 13 32 PM

I originally wanted to use that component but the error message comes off to me like the item is missing instead of the item just failing to load. Wouldn't that confuse the users making them think that an item has been deleted?

**Comment by theofficialnar** [comment]
> @theofficialnar The existing handling might be lacking so if anything I expect the current one to be updated as opposed to adding a nested child handling

@agalin920, yeah I guess I could just add that handling to show the error message you mentioned when the model is undefined. I checked how that message is being shown and currently it only shows up when the api call to fetch the model item failed.

**Comment by theofficialnar** [comment]
@agalin920, the original fix resolves the issue with the missing modelType which wasn't really used anyway. But another error occurs which also breaks the app just like before this was fixed pertaining to a missing model ZUID. Actually, I just realized just now that I can just use the model zuid that's on the url param.

**Comment by theofficialnar** [comment]
Added a more simpler fix @agalin920

**Pull request merged**
