### PR TITLE
Feature/duomode headless iframe

### PR DESCRIPTION
**Pull request by d88naimi**
In duo mode if the view is a headless content item then show Instant API

Screen Shot 2022-01-05 at 12 28 08 PM

### CODE REVIEW

**Review by shrunyan — COMMENTED** [review]
Why are you swapping the iframe url instead of the route passed to active preview?

**Comment by d88naimi** [comment]
@shrunyan  updated however now I have a hanging loading sign if you have a tip on how to resolve that?

Screen Shot 2022-01-05 at 5 58 12 PM

**Comment by shrunyan** [comment]
You'll need to look at the ActivePreview app to see why that appears that way.

**Comment by shrunyan** [comment]
Also look into adding `react-json-view` in ActivePreview to format the json output. You can see prior art of that usage here: https://github.com/zesty-io/start.zesty.io/blob/main/src/components/GettingStarted/components/Preview/Preview.js#L23

**Comment by d88naimi** [comment]
@shrunyan review por favor

Screen Shot 2022-01-10 at 12 17 54 PM

https://www.loom.com/share/b738b0caa0644fc0937fff0cd942c0e3

**Review by shrunyan — COMMENTED** [review]
The approach generally looks correct but I think this should occur inside of the ActivePreview app, not within the editor. Meaning the interface, the `route` prop, should remain the same but in the ActivePreview app it determines whether it should be showing the iframe or json preview

**Comment by d88naimi** [comment]
@stuart I am loading this ReactJSON through PreviewMode.js im not following why this needs to be moved in ActivePreview which is the Preview button https://github.com/zesty-io/manager-ui/blob/master/src/shell/components/global-actions/components/ActivePreview/ActivePreview.js#L122-L127

**Comment by d88naimi** [comment]
Screen Shot 2022-01-12 at 1 21 33 PM

**Pull request merged**
