### PR TITLE
Update marketplace json endpoint

### PR DESCRIPTION
**Pull request by agalin920**

### CODE REVIEW

**Review by finnar-bin — APPROVED** [review]
Are we planning on utilizing this url moving forward or is this going to be a temp fix?

**Comment by finnar-bin** [comment]
Gotcha, I thought this a dev preview link. Was concerned that unpublished announcements would be accidentally displayed.

**Comment by shrunyan** [comment]
I concur with @finnar-bin. I do not think this URL is what we want as it is a preview link and will ignore publishings data

**Comment by shrunyan** [comment]
I believe we want close this PR in favor of this API change https://github.com/zesty-io/webengine/pull/388

@agalin920 let me know if you disagree or if I'm incorrect with the linked PR

**Pull request closed without merging**
