### PR TITLE
Add media field thumbnails

### LINKED ISSUE #2448: Content: Media Field - File Thumbnails not loading (except for images)
**Problem**
The Media field list item is not showing the thumbnail preview for all file types (except images). This means that file types such as PDFs do not render any thumbnail and instead just an error message. 

image

CleanShot 2024-01-12 at 01 32 43

**Solution**
Please render the appropriate file thumbnail as done in the Media app
CleanShot 2024-01-12 at 01 33 37

### PR DESCRIPTION
**Pull request by theofficialnar**
[file-type-thumbs.webm](https://github.com/zesty-io/manager-ui/assets/28705606/4465488c-8075-445a-bcac-6d6accb9bce1)

Closes #2448

### CODE REVIEW

**Comment by theofficialnar** [comment]
@agalin920 going to look into that

**Comment by theofficialnar** [comment]
@agalin920 Updated to use `FileTypePreview` as suggested

**Review by zcolah — CHANGES_REQUESTED** [review]
Make the icon have a size of 40 x 40 instead of 60 x 60 

https://www.loom.com/share/92187d23d3a040238f2b4abac2236dd4?from_recorder=1&focus_title=1

**Review by zcolah — CHANGES_REQUESTED** [review]
CleanShot 2024-01-30 at 04 34 32

**Pull request merged**
