### PR TITLE
Content fields lag

### LINKED ISSUE #2463: Content: Typing experience is laggy when multiple fields are present
**Describe the bug**
When editing a content item with multiple fields, typing experience is very laggy

**To Reproduce**
1. Go to a content item with multiple fields
2. Start typing on any field
3. See issue

**Expected behavior**
Typing should not be laggy

**Screenshots**
[content-fields-lag.webm](https://github.com/zesty-io/manager-ui/assets/28705606/a4079004-c83b-4022-9b05-f632ff032164)

### PR DESCRIPTION
**Pull request by finnar-bin**
[content-fields-lag.webm](https://github.com/zesty-io/manager-ui/assets/28705606/c07ee60b-eeb3-4c61-8c62-8b571461fc45)

Closes #2463

### CODE REVIEW

**Review by zcolah — CHANGES_REQUESTED** [review]
Still facing lag: 

1. https://www.loom.com/share/7090831ffc23426ca4c8fe115e78f4cf?from_recorder=1&focus_title=1
2. https://www.loom.com/share/6388dcce9f3f49ccbca4ff6b7829311f?from_recorder=1&focus_title=1

**Comment by zcolah** [comment]
@agalin920 

1. Have not tested this PR recently so have lost context. My last memory is that we felt it was slow on dev and then it got deployed to stage but did not get tested as I think I got distracted by another important PR potentially. 

2. Because I found it difficult to see a noted difference, I do remember wanting more people than just myself to test the PR. May we request the following two additional people to test the improvement. 
- @shrunyan (since he created the issue)
- @giseleblair or @gtllien (from support to test)

3. Hence may we have it redeployed to stage @theofficialnar in the week after next?  This is because @shrunyan is out next week.

**Comment by theofficialnar** [comment]
@agalin920 The main change I made here was basically move some of the states closer to the components using them and restructuring how the error states are handled. I may need to update this PR again if @zcolah wants this redeployed to stage since a lot has changed since then. Based on my experience it did somehow made the fields a bit responsive although not that much since the current one on prod is also not that bad. I think when the issue was first reported it was probably seen on dev which is a bit slower than stage and prod.

**Comment by theofficialnar** [comment]
Closing this as it doesn't seem to be necessary anymore

**Pull request closed without merging**
