### PR TITLE
feature/lift duo mode refactor

### PR DESCRIPTION
**Pull request by d88naimi**
This PR is to resolve duo mode showing in Item Create view previously I was using some magic hiding to get the layout fixed. This restructures the code to be cleaner and more legible.  

- [x] Lift the DuoMode preview out of Editor.js and into /ItemEdit/Content/Content.js
- [x] Verified no physical changes on other browsers
- [x] Verified Item Create is working/looking as intended
- [x] Verified that Details Panel works properly as was not affected

### CODE REVIEW

**Comment by d88naimi** [comment]
@shrunyan this pr will fixes #957 https://github.com/zesty-io/manager-ui/issues/957

**Comment by shrunyan** [comment]
Is this PR about reorganizing DuoMode so it is lifted out of the editor or solving PR #957?

**Comment by d88naimi** [comment]
@shrunyan  this PR is both  "reorganizing DuoMode so it is lifted out of the editor or solving PR #957"

**Comment by shrunyan** [comment]
Please separate the two changes. I want to be able to distinguish between the code changes.

**Comment by shrunyan** [comment]
@d88naimi there is a merge conflict that needs to be resolved.

**Review by agalin920 — APPROVED** [review]
LGTM

**Review by shrunyan — APPROVED** [review]

**Pull request merged**
