### PR TITLE
fix: Media: Upload Modal - Title does not become plural

### PR DESCRIPTION
**Pull request by glespinosa**
Will close https://github.com/zesty-io/manager-ui/issues/2495

Since I can't reproduced the success uploading in the local environment cause it keeps failing to upload.
While testing I set a fixed value of 2 for filesUploaded variable to reproduce and check if the condition is now working fiine.

Note: pls ignore the failed uploading messages, since this is a local environment, when this is deployed in dev or prod this will work as intended.

[screencast-8-aaeffee09b-7w6v22.manager.dev.zesty.io_8080-2024.03.13-06_31_50.webm](https://github.com/zesty-io/manager-ui/assets/44116036/d1094671-9c55-4574-b4a9-4301f0d1a89a)

Creating new PR cause I made some unnecessary commits in my previous PR, thinking that I only have problem in my connectivity but looks like the github having some outage issue in PR. (https://www.githubstatus.com/incidents/q3gl44chgxwv)
https://github.com/zesty-io/manager-ui/pull/2587

### CODE REVIEW

**Review by zcolah — CHANGES_REQUESTED** [review]
@glespinosa 

- [ ] Please ensure the solution also handles the situation of "1 File Uploaded"  and "1 File Uploading". It should only make Files plural when the number is greater than 1.

**Comment by glespinosa** [comment]
> @glespinosa
> 
> * [ ]  Please ensure the solution also handles the situation of "1 File Uploaded"  and "1 File Uploading". It should only make Files plural when the number is greater than 1.

@zcolah Yes, I also tested on 1 file, its working fine

**Comment by zcolah** [comment]
@glespinosa 
pls see this loom to see what I mean 

https://www.loom.com/share/b8dba364225e4252ab101e1a99daf095

**Comment by glespinosa** [comment]
It seems like the above demo I showed was not sync correctly on the code, pls look on this one

[screencast-8-aaeffee09b-7w6v22.manager.dev.zesty.io_8080-2024.03.22-07_13_34 (1).webm](https://github.com/zesty-io/manager-ui/assets/44116036/1c61df06-763c-4bc2-8f40-d50b029b1688)

**Pull request merged**
